#!/usr/bin/env bash

curr_dir=$(readlink -e `dirname $0`)

set -e
#set -x
set -u


if [ -e $HOME/.confluencer.conf ]
then
  source $HOME/.confluencer.conf 
else 
  source $curr_dir/confluencer.conf
fi

confluence_page_title="$1"
input_html_path="$2"
tmp_json_path=`tempfile -s .confluencer.sent.json`
tmp_response=`tempfile -s .confluencer.response.json`

echo "html($input_html_path) -> json($tmp_json_path)..."
python $curr_dir/html_to_confluence_json.py "$confluence_space" "$input_html_path" "$confluence_page_title" "$confluence_page_ancestor" > "$tmp_json_path"

echo "Publishing json($tmp_json_path)..."
curl -v -u "$confluence_user" -X POST -H 'Content-Type: application/json' --data-binary "@$tmp_json_path" "$confluence_url/rest/api/content/" -o $tmp_response

if [ "$?" == "0" ]
then
  cat "$tmp_response" | python -m json.tool
  page_id=$(cat "$tmp_response" | egrep -o '"id":[0-9]+' | egrep -o "[0-9]+" | sort | uniq)
  echo ""
  echo ""
  echo "Parent      : $confluence_url/pages/viewpage.action?pageId=$confluence_page_ancestor"
  echo "Page (name) : $confluence_url/display/$confluence_space/$confluence_page_title"
  echo "Page (id)   : $confluence_url/pages/viewpage.action?pageId=$page_id"
  echo ""
  echo ""
else
  cat "$tmp_response"
  echo "Something went wrong!!!"
fi

 

